apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    email: support@stackrox.com
    owner: stackrox
  labels:
    app.kubernetes.io/component: sensor
    app.kubernetes.io/instance: stackrox-secured-cluster-services
    app.kubernetes.io/name: stackrox
    app.kubernetes.io/part-of: stackrox-secured-cluster-services
  name: manage-compliance
  namespace: openshift-compliance
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edit-compliance
subjects:
- kind: ServiceAccount
  name: sensor
  namespace: stackrox